fix test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -39,7 +39,7 @@ jobs:
       fail-fast: false
       matrix:
         os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04]
-        python: [3.5.4, 3.6.7, 3.7.5, 3.8.1]
+        python: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
     steps:
     - name: Checkout
       uses: actions/checkout@v2
@@ -62,34 +62,34 @@ jobs:
     - name: Run simple code
       run: python -c 'import math; print(math.factorial(5))'
 
-  setup-pre-release-version-from-manifest:
-    name: Setup 3.9.0-beta.4 ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04]
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
+  # setup-pre-release-version-from-manifest:
+  #   name: Setup 3.9.0-beta.4 ${{ matrix.os }}
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04]
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v2
 
-    - name: setup-python 3.9.0-beta.4
-      uses: ./
-      with:
-        python-version: '3.9.0-beta.4'
+  #   - name: setup-python 3.9.0-beta.4
+  #     uses: ./
+  #     with:
+  #       python-version: '3.9.0-beta.4'
 
-    - name: Validate version
-      run: |
-        $pythonVersion = (python --version)
-        if ("Python 3.9.0b4" -ne "$pythonVersion"){
-          Write-Host "The current version is $pythonVersion; expected version is 3.9.0b4"
-          exit 1
-        }
-        $pythonVersion
-      shell: pwsh
+  #   - name: Validate version
+  #     run: |
+  #       $pythonVersion = (python --version)
+  #       if ("Python 3.9.0b4" -ne "$pythonVersion"){
+  #         Write-Host "The current version is $pythonVersion; expected version is 3.9.0b4"
+  #         exit 1
+  #       }
+  #       $pythonVersion
+  #     shell: pwsh
 
-    - name: Run simple code
-      run: python -c 'import math; print(math.factorial(5))'
+  #   - name: Run simple code
+  #     run: python -c 'import math; print(math.factorial(5))'
 
   setup-pypy:
     name: Setup PyPy ${{ matrix.os }}
